ALTER TYPE "EventTeamStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "EventTeamStatus" ADD VALUE IF NOT EXISTS 'NEEDS_ATTENTION';

ALTER TYPE "EventTeamChangeRequestStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "EventTeamChangeRequestStatus" ADD VALUE IF NOT EXISTS 'WAITING_INVITEE';
ALTER TYPE "EventTeamChangeRequestStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';