export type ProfileFieldType =
  | 'text'
  | 'textarea'
  | 'date'
  | 'select'
  | 'phone'
  | 'boolean'
  | 'url'
  | 'country'
  | 'language'
  | 'language_level'
  | 'activity_status'
  | 'activity_direction'
  | 'gender'
  | 'document_type'
  | 'address';

export type ProfileSectionKey =
  | 'registration_data'
  | 'general_info'
  | 'personal_documents'
  | 'contact_data'
  | 'activity_info';

export interface ProfileFieldDefinition {
  key: string;
  sectionKey: ProfileSectionKey;
  type: ProfileFieldType;
  labelRu: string;
  labelEn: string;
  defaultVisibleInCabinet: boolean;
  allowEventRequirement: boolean;
  isCompositeRequirement: boolean;
  storageScope: 'user' | 'extended_profile' | 'identity_document' | 'international_passport' | 'social_links' | 'emergency_contact' | 'additional_language' | 'activity_direction' | 'additional_document';
}

export const PROFILE_FIELD_REGISTRY: ProfileFieldDefinition[] = [
  // registration_data section
  {
    key: 'lastNameCyrillic',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Фамилия (кириллица)',
    labelEn: 'Last Name (Cyrillic)',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'firstNameCyrillic',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Имя (кириллица)',
    labelEn: 'First Name (Cyrillic)',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'middleNameCyrillic',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Отчество (кириллица)',
    labelEn: 'Middle Name (Cyrillic)',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'lastNameLatin',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Фамилия (латиница)',
    labelEn: 'Last Name (Latin)',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'firstNameLatin',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Имя (латиница)',
    labelEn: 'First Name (Latin)',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'middleNameLatin',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Отчество (латиница)',
    labelEn: 'Middle Name (Latin)',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'hasNoLastName',
    sectionKey: 'registration_data',
    type: 'boolean',
    labelRu: 'Нет фамилии',
    labelEn: 'No Last Name',
    defaultVisibleInCabinet: false,
    allowEventRequirement: false,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'hasNoFirstName',
    sectionKey: 'registration_data',
    type: 'boolean',
    labelRu: 'Нет имени',
    labelEn: 'No First Name',
    defaultVisibleInCabinet: false,
    allowEventRequirement: false,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'hasNoMiddleName',
    sectionKey: 'registration_data',
    type: 'boolean',
    labelRu: 'Нет отчества',
    labelEn: 'No Middle Name',
    defaultVisibleInCabinet: false,
    allowEventRequirement: false,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'birthDate',
    sectionKey: 'registration_data',
    type: 'date',
    labelRu: 'Дата рождения',
    labelEn: 'Date of Birth',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'gender',
    sectionKey: 'registration_data',
    type: 'gender',
    labelRu: 'Пол',
    labelEn: 'Gender',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'citizenshipCountryCode',
    sectionKey: 'registration_data',
    type: 'country',
    labelRu: 'Гражданство',
    labelEn: 'Citizenship',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'residenceCountryCode',
    sectionKey: 'registration_data',
    type: 'country',
    labelRu: 'Страна проживания',
    labelEn: 'Country of Residence',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'phone',
    sectionKey: 'registration_data',
    type: 'phone',
    labelRu: 'Телефон',
    labelEn: 'Phone',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'telegram',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Telegram',
    labelEn: 'Telegram',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'consentPersonalData',
    sectionKey: 'registration_data',
    type: 'boolean',
    labelRu: 'Согласие на обработку персональных данных',
    labelEn: 'Personal Data Processing Consent',
    defaultVisibleInCabinet: false,
    allowEventRequirement: false,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'consentMailing',
    sectionKey: 'registration_data',
    type: 'boolean',
    labelRu: 'Согласие на рассылку',
    labelEn: 'Mailing Consent',
    defaultVisibleInCabinet: false,
    allowEventRequirement: false,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'avatarAssetId',
    sectionKey: 'registration_data',
    type: 'text',
    labelRu: 'Фотография',
    labelEn: 'Photo',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },

  // general_info section
  {
    key: 'nativeLanguage',
    sectionKey: 'general_info',
    type: 'language',
    labelRu: 'Родной язык',
    labelEn: 'Native Language',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'communicationLanguage',
    sectionKey: 'general_info',
    type: 'language',
    labelRu: 'Язык общения',
    labelEn: 'Communication Language',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'regionText',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Регион',
    labelEn: 'Region',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'districtText',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Район',
    labelEn: 'District',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'settlementText',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Город/населённый пункт',
    labelEn: 'City/Settlement',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'street',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Улица',
    labelEn: 'Street',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'house',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Дом',
    labelEn: 'House',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'apartment',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Квартира',
    labelEn: 'Apartment',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'postalCode',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Почтовый индекс',
    labelEn: 'Postal Code',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'city',
    sectionKey: 'general_info',
    type: 'text',
    labelRu: 'Город',
    labelEn: 'City',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'factualAddress',
    sectionKey: 'general_info',
    type: 'textarea',
    labelRu: 'Фактический адрес',
    labelEn: 'Actual Address',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'user',
  },
  {
    key: 'consentClientRules',
    sectionKey: 'general_info',
    type: 'boolean',
    labelRu: 'Согласие с правилами',
    labelEn: 'Terms Consent',
    defaultVisibleInCabinet: false,
    allowEventRequirement: false,
    isCompositeRequirement: false,
    storageScope: 'user',
  },

  // personal_documents section
  {
    key: 'documentType',
    sectionKey: 'personal_documents',
    type: 'document_type',
    labelRu: 'Тип документа',
    labelEn: 'Document Type',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'documentSeries',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'Серия документа',
    labelEn: 'Document Series',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'documentNumber',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'Номер документа',
    labelEn: 'Document Number',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'issueDate',
    sectionKey: 'personal_documents',
    type: 'date',
    labelRu: 'Дата выдачи',
    labelEn: 'Issue Date',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'issuedBy',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'Кем выдан',
    labelEn: 'Issued By',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'expiryDate',
    sectionKey: 'personal_documents',
    type: 'date',
    labelRu: 'Срок действия',
    labelEn: 'Expiry Date',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'placeOfBirth',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'Место рождения',
    labelEn: 'Place of Birth',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'pinfl',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'ПИНФЛ',
    labelEn: 'PINFL',
    defaultVisibleInCabinet: false,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'snils',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'СНИЛС',
    labelEn: 'SNILS',
    defaultVisibleInCabinet: false,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'passportSeries',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'Серия паспорта',
    labelEn: 'Passport Series',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'passportNumber',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'Номер паспорта',
    labelEn: 'Passport Number',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },
  {
    key: 'subdivisionCode',
    sectionKey: 'personal_documents',
    type: 'text',
    labelRu: 'Код подразделения',
    labelEn: 'Subdivision Code',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'identity_document',
  },

  // contact_data section
  {
    key: 'vkUrl',
    sectionKey: 'contact_data',
    type: 'url',
    labelRu: 'ВКонтакте',
    labelEn: 'VKontakte',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'social_links',
  },
  {
    key: 'telegramUrl',
    sectionKey: 'contact_data',
    type: 'url',
    labelRu: 'Telegram',
    labelEn: 'Telegram',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'social_links',
  },
  {
    key: 'instagramUrl',
    sectionKey: 'contact_data',
    type: 'url',
    labelRu: 'Instagram',
    labelEn: 'Instagram',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'social_links',
  },
  {
    key: 'facebookUrl',
    sectionKey: 'contact_data',
    type: 'url',
    labelRu: 'Facebook',
    labelEn: 'Facebook',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'social_links',
  },
  {
    key: 'xUrl',
    sectionKey: 'contact_data',
    type: 'url',
    labelRu: 'X (Twitter)',
    labelEn: 'X (Twitter)',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'social_links',
  },
  {
    key: 'maxUrl',
    sectionKey: 'contact_data',
    type: 'url',
    labelRu: 'MAX',
    labelEn: 'MAX',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'social_links',
  },

  // activity_info section
  {
    key: 'activityStatus',
    sectionKey: 'activity_info',
    type: 'activity_status',
    labelRu: 'Статус деятельности',
    labelEn: 'Activity Status',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'studiesInRussia',
    sectionKey: 'activity_info',
    type: 'boolean',
    labelRu: 'Учится в России',
    labelEn: 'Studies in Russia',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'organizationName',
    sectionKey: 'activity_info',
    type: 'text',
    labelRu: 'Название организации',
    labelEn: 'Organization Name',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'facultyOrDepartment',
    sectionKey: 'activity_info',
    type: 'text',
    labelRu: 'Факультет/отделение',
    labelEn: 'Faculty/Department',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'classCourseYear',
    sectionKey: 'activity_info',
    type: 'text',
    labelRu: 'Класс/курс/год',
    labelEn: 'Class/Course/Year',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'positionTitle',
    sectionKey: 'activity_info',
    type: 'text',
    labelRu: 'Должность',
    labelEn: 'Position',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'achievementsText',
    sectionKey: 'activity_info',
    type: 'textarea',
    labelRu: 'Достижения',
    labelEn: 'Achievements',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'englishLevel',
    sectionKey: 'activity_info',
    type: 'language_level',
    labelRu: 'Уровень английского',
    labelEn: 'English Level',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'russianLevel',
    sectionKey: 'activity_info',
    type: 'language_level',
    labelRu: 'Уровень русского',
    labelEn: 'Russian Level',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'extended_profile',
  },
  {
    key: 'additionalLanguages',
    sectionKey: 'activity_info',
    type: 'text',
    labelRu: 'Дополнительные языки',
    labelEn: 'Additional Languages',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'additional_language',
  },
  {
    key: 'activityDirections',
    sectionKey: 'activity_info',
    type: 'activity_direction',
    labelRu: 'Направления деятельности',
    labelEn: 'Activity Directions',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: true,
    storageScope: 'activity_direction',
  },
  {
    key: 'emergencyContact',
    sectionKey: 'activity_info',
    type: 'text',
    labelRu: 'Экстренный контакт',
    labelEn: 'Emergency Contact',
    defaultVisibleInCabinet: true,
    allowEventRequirement: true,
    isCompositeRequirement: false,
    storageScope: 'emergency_contact',
  },
];

export function getFieldByKey(key: string): ProfileFieldDefinition | undefined {
  return PROFILE_FIELD_REGISTRY.find((f) => f.key === key);
}

export function getFieldsBySection(sectionKey: ProfileSectionKey): ProfileFieldDefinition[] {
  return PROFILE_FIELD_REGISTRY.filter((f) => f.sectionKey === sectionKey);
}

export function getVisibleFieldsForRequirement(): ProfileFieldDefinition[] {
  return PROFILE_FIELD_REGISTRY.filter(
    (f) => f.defaultVisibleInCabinet && f.allowEventRequirement
  );
}

export const PROFILE_SECTION_LABELS: Record<ProfileSectionKey, { ru: string; en: string }> = {
  registration_data: { ru: 'Регистрационные данные', en: 'Registration Data' },
  general_info: { ru: 'Общая информация', en: 'General Info' },
  personal_documents: { ru: 'Документы', en: 'Personal Documents' },
  contact_data: { ru: 'Контакты и соцсети', en: 'Contacts & Social' },
  activity_info: { ru: 'Образование и деятельность', en: 'Education & Activity' },
};
